renderer/console.js
renderer/run.js

In order for this to work for me with the `--render` option, I needed to change your approach to hijacking `stdout.write`. I'm not sure if this is an Electron versioning issue, but the following changes resolve the issue for me.

Fix socket errors

---

README.md
args.js
mocha.js
renderer/run.js

In order to support mocha compilers, the CLI `--compilers` argument has been pulled to the `electron-mocha` front-end, which makes calls like ```electron-mocha --compilers js:babel/register test/example.js``` possible in case one has written tests in ES6 for example.

Support `--compilers` arg

---

index.js

I just did some testing of `process.exit(1)` in various versions of electron:
```
0.33.0 ×
0.33.1 ×
0.33.2 ×
0.33.3 ×
0.33.4 ×
0.33.5 ×
0.33.6 ×
0.33.7 ✔
0.33.8 ✔
0.34.0 ✔
```
So basically this is working for electron >= 0.33.7
Should I include a test for the electron version to ensure that electron-mocha is only started with a working electron version?

End electron with correct exit code

---

renderer/run.js
test/test3.js

There are some libraries, such as [angular-mocks](https://github.com/angular/bower-angular-mocks) that rely on mocha exposing itself to `window` to detect a testing environment.
`angular-mocks` for example, has the following code which uses to determine if `angular.mocks.module` and `angular.mocks.inject` should be declared, which are essential testing utilities in angular:
```js
if (window.jasmine || window.mocha) { ... }
```
See https://github.com/angular/bower-angular-mocks/blob/master/angular-mocks.js#L2448
Currently, `electron-mocha` doesn't expose mocha to `window`, therefore libraries like `angular-mocks` fail to detect a testing environment and lack expected functionality.
[mocha](http://mochajs.org) exposes itself like this:
```js
window.mocha = mocha
```
See …

Expose mocha to window in renderer context

---

README.md
args.js
index.js

This enables support for `mocha.opts` simply using the original mocha code.
Thanks for electron-mocha!

Add support for mocha.opts

---

bin/electron-mocha

```sh
$ electron-mocha ./tests # Some tests fail
$ echo $?
0
```
I found that `bin/electron-mocha` script didn't propagate exit status
properly.  I fixed it.

Fixed exit status on running command

---

index.js
renderer/console.js
renderer/run.js

*Removed index.js as it wasn't useful, repointed index.html to run.js
*Everywhere that requires an electron module first checks electron's version to apply proper syntax

Misc things + squash deprecation warning

---

args.js
index.js
renderer/run.js

This PR makes the -r/--require options load in browser/renderer depending on the --renderer switch. Without this, it is not possible to use the option to load helpers, custom matchers etc. into the renderer using -r/--require.
Fix #13

Add -r/--require support for renderer tests

---

renderer/console.js

Console.log implicitly adds line breaks; see #39 
Note: On Linux writes to process.stdout are written to the terminal, but on OS X they are not so it is still necessary to use the remote module.

Forward to main process.stdout not console.log

---

bin/electron-mocha

Addressing #47
Essentially the same, but works in intellij

addressing intellij and tee console issue

---

index.js

This fixes window preferences on the latest Electron. I know these things are nuisance... let me know if you want to handle it differently!
The preload option has also been moved to webPreferences -- shall I update electron-window, too?

Suppress 0.37+ deprecation warnings

---

args.js
renderer/run.js

See discussion at #45 
This essentially adds a `--preload` option which can be used like `--require` for non common js modules; those scripts will be loaded via extra script tags in the renderer.
Credit belongs to @orbitbot -- I just combined the resolving of preload/require to make it easier to maintain. (Tests to follow in separate PR)

Add option to preload script tags

---

bin/electron-mocha

Tries to fallback to a locally installed electon-prebuilt if electron can't be found in PATH or ELECTRON_PATH. This should fix #4

Fallback to local install of electron-prebuilt

---

index.js

window must be destroyed before electron exit

---

index.js
mocha.js
renderer/run.js

Fix #57 
This moves handling the `--require` option into the mocha file, to make sure that `--compilers` have already been loaded. @jprichardson can you confirm that this is OK?

Handle --compiler before --require options

---

index.js
renderer/console.js
renderer/run.js

@jprichardson are we ready for this or would you prefer to wait? (We could update the major version to make sure no one on Electron 0.x pulls this in)

Remove Electron 0.x API calls / checks

---

README.md
args.js
index.js
renderer/index.html
renderer/run.js

Somewhat related to #68 this adds debugger support.
By default, Electron sees our command line switches, so passing `--debug` or `--debug-brk` is actually handled by Electron. This PR adds both switches  to our options list to make sure that we don't halt because these options were passed (but we don't do anything with them).
#68 was asking for VS Code support -- this could probably be made to work using [the debugger protocol](http://electron.atom.io/docs/api/web-contents/#webcontentsdebugger) but we can't implement this kind of integration in electron-mocha.
Instead, this PR adds a way to debug renderer tests using the built-in debugger. When you run the tests with `--renderer-debug` we will show the test runner window and open the dev-tools; futhermore, in my testing I noticed that …

Add debugger support

---

appveyor.yml
index.js
test/renderer/indexed-db-test.js

On Windows, tests that access `indexedDB` (and other things) will fail on exit with an `EBUSY` error when the temp directory is deleted.
This is because even though the `closed` event has fired on the `BrowserWindow`, its `webContents` may not have been deleted yet and could still be holding file locks.
This pull request switches the `app.exit` call to be done when the `'destroyed'` event on `win.webContents` fires.
```
Error: EBUSY: resource busy or locked, unlink 'C:\Users\appveyor\AppData\Local\Temp\1\electron-mocha-8Cl0bn\databases\Databases.db'
at Error (native)
at Object.fs.unlinkSync (fs.js:1099:18)
at rimrafSync (C:\projects\electron-mocha\node_modules\rimraf\rimraf.js:305:17)
at C:\projects\electron-mocha\node_modules\rimraf\rimraf.js:340:5
at Array.forEach (native)
at rmkidsSync …
```

Exit after webContents destroyed event fires

---

README.md
args.js
index.js
test/main/opts_test.js
test/mocha.opts
test/renderer/opts_test.js
test/support/requireMain.js

This will allow loading main process test utils when testing in the renderer process.  Mocking the `remote` module in electron is iffy at the best of times so if we can require modules in the main process to help us mock the actual main process implementation it will make testing things in the renderer a lot easier 👍

Add a --require-main option

---

index.js

Addresses #86. Also testing #75 (since I'm on a Mac), the only time my workspace is changed to the one with electron-mocha running is when the `--debug-brk` flag is present, thus I believe that issue is also resolved.

Allow focus when debugging tests

---

args.js
index.js
renderer/run.js

This adds a new `--interactive` option which is similar to `--debug --renderer` but does not close the Electron window when tests finish running. Tests can be re-run by reloading the window and all output goes to the dev tools console rather than the terminal.
This streamlines the workflow when making heavy use of the dev tools during TDD sessions. Objects such as DOM nodes can be visualized in the console more easily than they can in the terminal, and the feedback loop is shorter when you only need to reload the window to re-run tests.
I have allowed edits from maintainers, so feel free to adjust this. Thanks! 🙇

Add `--interactive` mode

---

index.js
renderer/run.js

Mocha registers exception handlers (work in main and renderer) to handle async test failures. If we handle uncaught exceptions (and exit) the test suite will not run to completion. See #93 
I think the best approach is actually for us to not handle uncaught errors at all since Mocha will handle them anyway. I have not had time to add tests for this (would be nice, but requires some effort, because it would have to be an integration test to be useful really). But I tested this with some of my own projects and made sure that if I throw errors in a test or hook they're picked up, so I hope this is good to merge.

Remove uncaught exception errors

---

index.js
renderer/run.js

Otherwise tests only run once on the initial window open and nothing happens on page reload.
Fixes #96

Trigger 'mocha-start' on page reload

---

cleanup.js
index.js

This is addressing the same thing https://github.com/jprichardson/electron-mocha/pull/103 was trying to address. See also https://github.com/electron/electron/issues/9583, https://github.com/electron/electron/issues/8685 and https://github.com/jprichardson/electron-mocha/issues/98.
The root of the problem is that `electron-mocha` would try to delete Electron's `userData` directory out from under it while it was still running. That happened to work sometimes, but as those issues show, it's pretty fragile.
Instead, we could spawn a separate task to clean up after Electron's quit.

Run clean up in a separate task

---

bin/electron-mocha

Sorry guys! Turns out `electron-compile` doesn't actually use `electron` underneath, it just depends on `electron-prebuilt-compile`, so we can't `resolve('electron-compile')`. So #111 won't work if the user has `electron-compile` as a dependency.
Since `electron-compile` depends on its prebuilt counterpart, we can just `resolve` that and it will work in both cases (whether they have `electron-compile` or just `electron-prebuilt-compile`).

fix for electron-compile support

---

index.js

Long running tests or test that need to wait for a given time could lead to the OS suspend the app or reduce its cpu time.
This leads to lesser precision for `setTimeout` or `setInterval` execution.
Fixes #128

Disable power save app suspension

---

index.js

This PR fixes the artificial constraint put on `--require-main` which previously would only load the given script if _only one_ `--require-main` argument is given. 
This behaviour is confusing because it would do nothing when providing two scripts via `--require-main` and misleading at best. In contrast, the `--require` argument allows for multiple scripts to be provided.
The rationale behind loading multiple scripts is to preload Babel or TypeScript transpilers to be able to run modern JavaScript as preload scripts. 
In my case, I use one script for the main electron process in order to turn off logging to file for the tested components (I use `electron-log`) and in the renderer process I do preload Chai extensions and configure Enzyme.
```
cross-env NODE_ENV=test electron-mocha …
```

Enable loading multiple --require-main scripts

---

README.md

Adding:
sh -e /etc/init.d/xvfb start
results in the following error:
sh: 0: Can't open /etc/init.d/xvfb
see: https://benlimmer.com/2019/01/14/travis-ci-xvfb/

fix travis CI configuration for Xenial build

---

lib/run.js

Just spent a while tracking down an error in some wrapper code where the error had no stack track associated with it - to get the stack trace to show I had to make this change.

Respect the full-trace option to show stack traces on error

---

lib/cleanup.js

Hello, 
I have Electron builds with disabled "run as node" feature (for security reasons) and electron-mocha works just fine with that, but cleanup script process never exits because it's not running "as node" but as "as electron". As a result I have bunch of electron processes hanging around, here's how it looks for me 😄 :  
Would you mind merging this small change which will fix my use-case? It's not breaking normal Electron in any way and it's in line with the current code, just explicitly exiting the app.
Thank you 🙇

Explicitly exit from cleanup script

---

lib/run.js
renderer/index.html
renderer/run.js

Bundlers export automatically-generated index.html which links to the compiled JavaScript code, CSS, etc... 
By not having the option to load a custom index.html you need to create a script and load with (`--script or --preload`) and create the `<script/>` s and  `<link/>`s in live, which is so painful.
Although this would eventually work, then comes another problem. The images cannot load because the index.html is in another place so the relative paths break.
Also, https://github.com/jprichardson/electron-mocha/issues/117
Add a argument to the cli (`--index`, that was my choice) which allows you to load your custom index.html.
This can be handy with automatically-generated `index.html` by bundlers.

:feature: Allow custom index.html

---

lib/run.js
package.json
renderer/run.js

`--script` ( alias `--preload`) injects a script tag, which is ok. But, --preload should have a totally different behavior, it should be loaded before the website even loads, not as a script.
Make `--preload` a standalone option instead of an alias of `--script` and be runned as a preload script like ElectronJS  Docs say.
👍🏻

Corrected --preload behavior

---

.travis.yml

The logic seems to be inverted now.

ci: allow builds targeting Electron "beta" to fail

---

lib/run.js
renderer/console.js

Electron allows disabling "remote" module at build time.
Let's make "electron-mocha" work for such builds.
Avoid using "remote" module and use IPC calls
for console logging in non-interactive renderers.
Based on what Electron itself does for its tests
https://github.com/electron/electron/blob/22cb3cd18b1b771364edada515a4c138a8dddc6d/spec/static/main.js#L55-L63
https://github.com/electron/electron/blob/22cb3cd18b1b771364edada515a4c138a8dddc6d/spec/static/index.html#L18-L27

refactor: do not use "remote" module for console calls

---

renderer/run.js

This lead to electron-mocha hanging in `--interactive` in case there was an exception in preload (e.g. ts-node/register).

Fix uncaught promise rejection

---

README.md
lib/run.js

Allow custom electron window options. See #171 for motivation.
Also changes `focusable` default to `true` on renderer (fixes #171).

Add `window-config-file` option

---

lib/mocha.js

```
✖ ERROR: watchRun is not a function
TypeError: watchRun is not a function
at Object.runMocha (/home/artem/projects/browser-monkey/node_modules/electron-mocha/lib/mocha.js:31:11)
```
Note: I wasn't able to see it actually rerunning tests on file changes, even after fixing the code.

Fix broken import

---

package-lock.json
package.json

This PR update `standard` to the next version (v17) coming soon and fixes linting issues (using `standard --fix`).
This allows having the `test-external` of `standard` passing for `jprichardson/electron-mocha`, before releasing to stable, we ensure that the ecosystem can easily upgrade without issues.
Related: https://github.com/standard/standard/issues/1777
This new version includes:
- [`object-shorthand` rule](https://github.com/standard/eslint-config-standard/pull/166) (as warning)
- Support for ESLint v8
- `--verbose` by default

style: fix new `standard` linting

---

renderer/run.js

When mocha failed, electron will be forced to exit and print error in command line.
It's not convienient when error thrown by imported scripts, so I change to print error stack in console in interactive mode
e.g:
```js
// error in myFoo will shut down electron
const foo = require('myFoo');
describe('bar', () => {
it('case', () => {});
});
```

Print error in console when mocha failed in interactive mode

---

lib/mocha.js
package.json
test/main/esm_test.mjs
test/main/opts_test.js
test/support/requireES.mjs

Use mocha's `loadFilesAsync()` to allow `--require` files and test files themselves to be ES modules.
We can't support `--require-main` files being ES modules because the loading is async, so we can't guarantee that they'll run before the app is ready.

Support ES modules in main process testing
